In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pickle as pk

In [6]:
dataset =  pd.read_csv("C:/Users/balar/Desktop/AI/Machine_learning/Advertising.csv",index_col=0)
dataset.head()
inputFeature = ['TV', 'radio', 'newspaper']
outputFeature = ['sales']
x = dataset[inputFeature]
y = dataset[outputFeature]
x.head()

TV  radio  newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [7]:
y.head()

sales
1   22.1
2   10.4
3    9.3
4   18.5
5   12.9

In [8]:
#step-2 split dataset
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=3)
x.shape

(200, 3)

In [9]:
xtrain.shape

(160, 3)

In [10]:
xtest.shape

(40, 3)

In [11]:
xtrain.head()

TV  radio  newspaper
157   93.9   43.5       50.5
116   75.1   35.0       52.7
156    4.1   11.6        5.7
16   195.4   47.7       52.9
62   261.3   42.7       54.7

In [12]:
model = LinearRegression()

In [13]:
model.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
ypred = model.predict(xtest)

In [15]:
error = np.sqrt(mean_squared_error(ytest,ypred))

In [16]:
error

1.4675768823681998

In [31]:
test = [151.5,41.3,58.5] # output => 18.5

In [32]:
model.predict([test])

array([[17.52440317]])

In [33]:
model.coef_

array([[0.04552917, 0.18512403, 0.00119881]])

In [34]:
model.intercept_

array([2.91098086])

In [35]:
value = 0


In [36]:
for x,b in zip(test,[0.04552917, 0.18512403, 0.00119881]):
     value += (x*b)

In [37]:
# model file creation
pk.dump(model,open("icebergModel.model","wb"))
import pickle as pk
loadedModel = pk.load(open("icebergModel.model","rb"))
loadedModel.predict([test])

array([[17.52440317]])

In [17]:
error/18.5

0.0793284801280108