In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pickle as pk

In [13]:
dataset =  pd.read_csv("C:/Users/balar/Desktop/AI/Machine_learning/USA_Housing.csv")
dataset.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0       79545.45857             5.682861                   7.009188   
1       79248.64245             6.002900                   6.730821   
2       61287.06718             5.865890                   8.512727   
3       63345.24005             7.188236                   5.586729   
4       59982.19723             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09      23086.80050  1.059034e+06   
1                          3.09      40173.07217  1.505891e+06   
2                          5.13      36882.15940  1.058988e+06   
3                          3.26      34310.24283  1.260617e+06   
4                          4.23      26354.10947  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [14]:
inputFeature = ['Avg. Area Income','Avg. Area House Age', 'Avg. Area Number of Rooms','Avg. Area Number of Bedrooms','Area Population']
outputFeature = ['Price']
x = dataset[inputFeature]
y = dataset[outputFeature]
x.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0       79545.45857             5.682861                   7.009188   
1       79248.64245             6.002900                   6.730821   
2       61287.06718             5.865890                   8.512727   
3       63345.24005             7.188236                   5.586729   
4       59982.19723             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population  
0                          4.09      23086.80050  
1                          3.09      40173.07217  
2                          5.13      36882.15940  
3                          3.26      34310.24283  
4                          4.23      26354.10947

In [15]:
y.head()

Price
0  1.059034e+06
1  1.505891e+06
2  1.058988e+06
3  1.260617e+06
4  6.309435e+05

In [16]:
#step-2 split dataset
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=3)
x.shape

(5000, 5)

In [17]:
xtrain.shape

(4000, 5)

In [18]:
xtest.shape

(1000, 5)

In [19]:
xtrain.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
2983       79095.27923             6.666809                   6.738534   
2181       60325.98588             6.812452                   7.647439   
4054       68061.81430             5.776912                   8.067646   
4748       80182.09303             3.738593                   9.654556   
4969       73299.37848             4.213338                   7.012554   

      Avg. Area Number of Bedrooms  Area Population  
2983                          2.50      23624.24894  
2181                          6.45      38418.05830  
4054                          3.02      30689.30260  
4748                          3.37      15090.85119  
4969                          4.46      45214.48851

In [20]:
model = LinearRegression()

In [21]:
model.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
ypred = model.predict(xtest)

In [23]:
error = np.sqrt(mean_squared_error(ytest,ypred))

In [24]:
error

103810.23007967715

In [25]:
test = [73299.37848,4.213338,7.012554,4.46,45214.48851] # output => 1260814.432
test1 = [65510.5818,5.992305307,6.792336104,4.07,46501.2838] #1298950.48

In [26]:
model.predict([test])

array([[1184112.23815694]])

In [27]:
model.coef_

array([[2.14390878e+01, 1.65080344e+05, 1.21791417e+05, 1.35158996e+03,
        1.51184366e+01]])

In [28]:
model.intercept_

array([-2626568.2150415])

In [29]:
value = 0


In [30]:
for x,b in zip(test,[2.14390878e+01, 1.65080344e+05, 1.21791417e+05, 1.35158996e+03,
        1.51184366e+01]):
     value += (x*b)

In [31]:
value

3810680.454956904

In [32]:
value + model.intercept_ - 1260814.432

array([-76702.19208459])

In [54]:
# model file creation
import pickle as pk
pk.dump(model,open("m-linreg-housing.model","wb"))

In [55]:
loadedModel = pk.load(open("m-linreg-housing.model","rb"))

In [56]:
error = np.sqrt(mean_squared_error(ytest,ypred))

In [57]:
error/1232072.654

0.08425658157629813

In [58]:
1184112.23815694/1260814.432

0.9391645654615572